name: Master Build

on:
  push:
    branches: [ master ]
#    paths:
#      - '.github/workflows/master-build.yml'
  pull_request:
    branches: [ master ]

jobs:
  master-build:
    #    name: build the app and image
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: kruft/dockerhub-pulllimits-exporter

    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Login in DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${DOCKER_IMAGE}

      - name: Push Docker image on DockerHub
        run: docker push  ${DOCKER_IMAGE}
